AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 60
    Handler: src/index.handler
    Architectures:
      - arm64

Resources:
  IAMCreateAccount:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Policies:
        - PolicyName: Route53
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'route53:*'
                Resource: '*'

  FunctionCreateAccount:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createAndUpdateAccount/
      Role: !GetAtt IAMCreateAccount.Arn
      Environment:
        Variables:
          AcmeParametersPrefix: !Ref AcmeParametersPrefix
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        BaseDirectory: createAndUpdateAccount

  FunctionCreateAccountPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionCreateAccount
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com

  FunctionCreateCertificate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createAndUpdateCertificate/
      Timeout: 600 # 200
      Role: !GetAtt IAMCreateAccount.Arn
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        BaseDirectory: createAndUpdateCertificate

  FunctionCreateCertificatePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionCreateCertificate
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com

Outputs:
  FunctionCreateAccountArn:
    Value: !GetAtt FunctionCreateAccount.Arn
  FunctionCreateCertificateArn:
    Value: !GetAtt FunctionCreateCertificate.Arn
